# Generated by Django 4.2.5 on 2023-09-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_productcategory_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='url_title',
            field=models.CharField(max_length=300, unique=True, verbose_name='عنوان در url'),
        ),
    ]
